"use client"

import { useState, useEffect } from "react"
import { motion } from "framer-motion"
import { cn } from "@/lib/utils"

const blockchainTerms = [
  {
    term: "Blockchain",
    definition: "A distributed, decentralized, public ledger that exists across a network.",
  },
  {
    term: "Smart Contract",
    definition: "Self-executing contracts with terms directly written into code.",
  },
  {
    term: "Hash",
    definition: "A fixed-length string generated by cryptographic algorithms to represent data.",
  },
  {
    term: "Node",
    definition: "Any active electronic device that maintains copies of the blockchain and keeps the network functioning.",
  },
  {
    term: "Consensus",
    definition: "Mechanism to agree on a single data value among distributed systems or processes.",
  },
  {
    term: "Wallet",
    definition: "A tool that allows users to interact with the blockchain and manage crypto assets.",
  },
]

export default function BlockchainTerms() {
  const [activeIndex, setActiveIndex] = useState(0)

  useEffect(() => {
    const interval = setInterval(() => {
      setActiveIndex((prev) => (prev + 1) % blockchainTerms.length)
    }, 5000)
    return () => clearInterval(interval)
  }, [])

  const radius = 200

  return (
    <div className="relative min-h-[600px] w-full overflow-hidden p-8">
      {/* Animated background particles */}
      <div className="absolute inset-0 opacity-20">
        {Array.from({ length: 50 }).map((_, i) => (
          <motion.div
            key={i}
            className="absolute h-0.5 w-0.5 rounded-full bg-green-400"
            initial={{
              x: `${Math.random() * 100}%`,
              y: `${Math.random() * 100}%`,
            }}
            animate={{
              x: `${Math.random() * 100}%`,
              y: `${Math.random() * 100}%`,
            }}
            transition={{
              duration: Math.random() * 10 + 5,
              repeat: Infinity,
              repeatType: "reverse",
            }}
          />
        ))}
      </div>

      {/* Term constellation */}
      <div className="relative z-10 mx-auto max-w-4xl">
        {blockchainTerms.map((term, index) => {
          const angle = (index * 360) / blockchainTerms.length
          const x = radius * Math.cos((angle * Math.PI) / 180)
          const y = radius * Math.sin((angle * Math.PI) / 180)

          return (
            <motion.div
              key={term.term}
              className={cn(
                "absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2",
                "cursor-pointer rounded-xl border border-white/10 bg-black/50 p-4 backdrop-blur-xl",
                "hover:bg-green-400/10 hover:border-green-400/30 transition-all"
              )}
              animate={{
                x,
                y,
                scale: activeIndex === index ? 1.2 : 1,
                opacity: activeIndex === index ? 1 : 0.6,
                zIndex: activeIndex === index ? 1 : 0,
              }}
              transition={{ type: "spring", stiffness: 100 }}
              onHoverStart={() => setActiveIndex(index)}
            >
              <h3 className="font-mono text-green-400">{term.term}</h3>
            </motion.div>
          )
        })}

        {/* Central definition prism */}
        <motion.div
          className="relative z-20 mt-32 flex h-[400px] items-center justify-center rounded-3xl border border-white/10 bg-gradient-to-br from-black/50 to-green-400/10 p-8 backdrop-blur-2xl"
          animate={{
            rotateY: activeIndex * 10,
          }}
          transition={{ type: "spring", stiffness: 50 }}
        >
          <div className="text-center">
            <motion.div
              key={activeIndex}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              className="space-y-6"
            >
              <div className="inline-block rounded-full bg-gradient-to-r from-green-400 to-cyan-500 p-1">
                <div className="rounded-full bg-black/80 px-6 py-2 backdrop-blur-lg">
                  <h2 className="font-mono text-2xl font-bold text-transparent bg-gradient-to-r from-green-400 to-cyan-400 bg-clip-text">
                    {blockchainTerms[activeIndex].term}
                  </h2>
                </div>
              </div>
              <motion.p
                className="mx-auto max-w-2xl text-lg leading-relaxed text-neutral-300"
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                transition={{ delay: 0.2 }}
              >
                {blockchainTerms[activeIndex].definition}
              </motion.p>
            </motion.div>
          </div>

          {/* Holographic grid */}
          <div className="absolute inset-0 rounded-3xl opacity-20 [mask-image:radial-gradient(ellipse_at_center,white,transparent_70%)]">
            <div className="h-full w-full bg-[url('data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAwJSIgaGVpZ2h0PSIyMDAlIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciPjxyZWN0IHdpZHRoPSIxMDAlIiBoZWlnaHQ9IjEwMCUiIGZpbGw9Im5vbmUiIHN0cm9rZT0iIzQwZDk3OSIgc3Ryb2tlLXdpZHRoPSIyIiBvcGFjaXR5PSIwLjEiLz48L3N2Zz4=')]" />
          </div>
        </motion.div>
      </div>

      {/* Optional: animated connection lines — removed due to complexity of % math */}
    </div>
  )
}
